// seed-data.js — Dados para cadastro global em massa
const SEED_ANIMES = [
  {nome:'Fullmetal Alchemist: Brotherhood',estudio:'Bones',genero:'Ação, Aventura, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg'},
  {nome:'Death Note',estudio:'Madhouse',genero:'Suspense, Sobrenatural',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/9/9453l.jpg'},
  {nome:'Shingeki no Kyojin',estudio:'Wit Studio',genero:'Ação, Drama, Suspense',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/10/47347l.jpg'},
  {nome:'Steins;Gate',estudio:'White Fox',genero:'Ficção Científica, Suspense',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/5/73199l.jpg'},
  {nome:'Hunter x Hunter (2011)',estudio:'Madhouse',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg'},
  {nome:'Code Geass',estudio:'Sunrise',genero:'Ação, Mecha, Drama',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/5/50331l.jpg'},
  {nome:'Cowboy Bebop',estudio:'Sunrise',genero:'Ação, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/4/19644l.jpg'},
  {nome:'Mob Psycho 100',estudio:'Bones',genero:'Ação, Comédia',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/8/80356l.jpg'},
  {nome:'Vinland Saga',estudio:'Wit Studio',genero:'Ação, Aventura, Drama',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1500/103005l.jpg'},
  {nome:'Jujutsu Kaisen',estudio:'MAPPA',genero:'Ação, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg'},
  {nome:'Demon Slayer',estudio:'ufotable',genero:'Ação, Sobrenatural',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg'},
  {nome:'My Hero Academia',estudio:'Bones',genero:'Ação, Super Poderes',temporadas:7,capa:'https://cdn.myanimelist.net/images/anime/10/78745l.jpg'},
  {nome:'Naruto Shippuden',estudio:'Pierrot',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/5/17407l.jpg'},
  {nome:'Dragon Ball Super',estudio:'Toei Animation',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/7/74606l.jpg'},
  {nome:'Bleach: Thousand-Year Blood War',estudio:'Pierrot',genero:'Ação, Aventura',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/1908/135431l.jpg'},
  {nome:'Chainsaw Man',estudio:'MAPPA',genero:'Ação, Terror',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg'},
  {nome:'Spy x Family',estudio:'Wit Studio',genero:'Ação, Comédia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg'},
  {nome:'Neon Genesis Evangelion',estudio:'Gainax',genero:'Mecha, Drama, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1314/108941l.jpg'},
  {nome:'Gintama',estudio:'Sunrise',genero:'Ação, Comédia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/10/73274l.jpg'},
  {nome:'One Punch Man',estudio:'Madhouse',genero:'Ação, Comédia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/12/76049l.jpg'},
  {nome:'Re:Zero',estudio:'White Fox',genero:'Drama, Fantasia, Suspense',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1522/128039l.jpg'},
  {nome:'Violet Evergarden',estudio:'Kyoto Animation',genero:'Drama, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1795/95088l.jpg'},
  {nome:'Made in Abyss',estudio:'Kinema Citrus',genero:'Aventura, Drama, Fantasia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/6/86733l.jpg'},
  {nome:'Sword Art Online',estudio:'A-1 Pictures',genero:'Ação, Aventura, Fantasia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/11/39717l.jpg'},
  {nome:'Tokyo Ghoul',estudio:'Pierrot',genero:'Ação, Terror, Sobrenatural',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/5/64449l.jpg'},
  {nome:'Parasyte',estudio:'Madhouse',genero:'Ação, Terror, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/3/73178l.jpg'},
  {nome:'Mushoku Tensei',estudio:'Studio Bind',genero:'Aventura, Drama, Fantasia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1530/117776l.jpg'},
  {nome:'Bocchi the Rock!',estudio:'CloverWorks',genero:'Comédia, Música',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1448/127956l.jpg'},
  {nome:'Frieren: Beyond Journey\'s End',estudio:'Madhouse',genero:'Aventura, Drama, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg'},
  {nome:'Solo Leveling',estudio:'A-1 Pictures',genero:'Ação, Aventura, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1908/141575l.jpg'},
  {nome:'Oshi no Ko',estudio:'Doga Kobo',genero:'Drama, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1812/134736l.jpg'},
  {nome:'Your Lie in April',estudio:'A-1 Pictures',genero:'Drama, Música, Romance',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/3/67177l.jpg'},
  {nome:'Haikyuu!!',estudio:'Production I.G',genero:'Esportes, Comédia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/7/76014l.jpg'},
  {nome:'Toradora!',estudio:'J.C.Staff',genero:'Comédia, Romance',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/5/22894l.jpg'},
  {nome:'Clannad: After Story',estudio:'Kyoto Animation',genero:'Drama, Romance',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1299/110774l.jpg'},
  {nome:'Erased',estudio:'A-1 Pictures',genero:'Mistério, Suspense',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/10/77957l.jpg'},
  {nome:'The Promised Neverland',estudio:'CloverWorks',genero:'Mistério, Suspense',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1830/118780l.jpg'},
  {nome:'Samurai Champloo',estudio:'Manglobe',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1375/121599l.jpg'},
  {nome:'Black Clover',estudio:'Pierrot',genero:'Ação, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/2/88336l.jpg'},
  {nome:'Fire Force',estudio:'David Production',genero:'Ação, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1286/101640l.jpg'},
  {nome:'Dr. Stone',estudio:'TMS Entertainment',genero:'Aventura, Ficção Científica',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/1613/102576l.jpg'},
  {nome:'Overlord',estudio:'Madhouse',genero:'Ação, Aventura, Fantasia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/7/88019l.jpg'},
  {nome:'Konosuba',estudio:'Studio Deen',genero:'Aventura, Comédia, Fantasia',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/8/77831l.jpg'},
  {nome:'Assassination Classroom',estudio:'Lerche',genero:'Ação, Comédia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/5/75639l.jpg'},
  {nome:'Noragami',estudio:'Bones',genero:'Ação, Aventura, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/9/67899l.jpg'},
  {nome:'Dororo',estudio:'MAPPA',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1879/100467l.jpg'},
  {nome:'Blue Lock',estudio:'8bit',genero:'Esportes',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1258/126929l.jpg'},
  {nome:'Kaiju No. 8',estudio:'Production I.G',genero:'Ação, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1137/141622l.jpg'},
  {nome:'Dandadan',estudio:'Science SARU',genero:'Ação, Comédia, Sobrenatural',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1032/142083l.jpg'},
  {nome:'Hell\'s Paradise',estudio:'MAPPA',genero:'Ação, Aventura, Sobrenatural',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1002/133399l.jpg'},
];

const SEED_DESENHOS = [
  {nome:'Apenas um Show',produtora:'Cartoon Network',temporadas:8},{nome:'Hora de Aventura',produtora:'Cartoon Network',temporadas:10},
  {nome:'O Incrível Mundo de Gumball',produtora:'Cartoon Network',temporadas:6},{nome:'Steven Universe',produtora:'Cartoon Network',temporadas:5},
  {nome:'Bob Esponja',produtora:'Nickelodeon',temporadas:14},{nome:'Avatar: A Lenda de Aang',produtora:'Nickelodeon',temporadas:3},
  {nome:'Jovens Titãs',produtora:'Cartoon Network',temporadas:5},{nome:'Ben 10',produtora:'Cartoon Network',temporadas:4},
  {nome:'Gravity Falls',produtora:'Disney',temporadas:2},{nome:'Rick and Morty',produtora:'Adult Swim',temporadas:7},
  {nome:'As Meninas Superpoderosas',produtora:'Cartoon Network',temporadas:6},{nome:'O Laboratório de Dexter',produtora:'Cartoon Network',temporadas:4},
  {nome:'Samurai Jack',produtora:'Cartoon Network',temporadas:5},{nome:'Coragem, o Cão Covarde',produtora:'Cartoon Network',temporadas:4},
  {nome:'KND: A Turma do Bairro',produtora:'Cartoon Network',temporadas:6},{nome:'Du, Dudu e Edu',produtora:'Cartoon Network',temporadas:6},
  {nome:'Danny Phantom',produtora:'Nickelodeon',temporadas:3},{nome:'Padrinhos Mágicos',produtora:'Nickelodeon',temporadas:10},
  {nome:'Invasor Zim',produtora:'Nickelodeon',temporadas:2},{nome:'A Vida Moderna de Rocko',produtora:'Nickelodeon',temporadas:4},
  {nome:'Liga da Justiça Sem Limites',produtora:'Warner Bros',temporadas:3},{nome:'Batman: A Série Animada',produtora:'Warner Bros',temporadas:4},
  {nome:'X-Men: Evolution',produtora:'Warner Bros',temporadas:4},{nome:'Super Choque',produtora:'Warner Bros',temporadas:4},
  {nome:'Phineas e Ferb',produtora:'Disney',temporadas:4},{nome:'Kim Possible',produtora:'Disney',temporadas:4},
  {nome:'Mutante Rex',produtora:'Cartoon Network',temporadas:3},{nome:'Mansão Foster para Amigos Imaginários',produtora:'Cartoon Network',temporadas:6},
  {nome:'As Terríveis Aventuras de Billy e Mandy',produtora:'Cartoon Network',temporadas:6},{nome:'Chowder',produtora:'Cartoon Network',temporadas:3},
  {nome:'Os Jovens Titãs em Ação',produtora:'Cartoon Network',temporadas:8},{nome:'A Casa Coruja',produtora:'Disney',temporadas:3},
  {nome:'Amphibia',produtora:'Disney',temporadas:3},{nome:'O Segredo Além do Jardim',produtora:'Cartoon Network',temporadas:1},
  {nome:'Trem Infinito',produtora:'Cartoon Network',temporadas:4},{nome:'Acampamento de Verão',produtora:'Cartoon Network',temporadas:6},
  {nome:'Craig do Riacho',produtora:'Cartoon Network',temporadas:5},{nome:'Vilanesco',produtora:'Cartoon Network',temporadas:1},
  {nome:'Arcane',produtora:'Netflix',temporadas:2},{nome:'Castlevania',produtora:'Netflix',temporadas:4},
  {nome:'Invencível',produtora:'Amazon Prime',temporadas:2},{nome:'A Lenda de Korra',produtora:'Nickelodeon',temporadas:4},
  {nome:'Tartarugas Ninja (2012)',produtora:'Nickelodeon',temporadas:5},{nome:'O Espetacular Homem-Aranha',produtora:'Sony',temporadas:2},
  {nome:'Justiça Jovem',produtora:'Warner Bros',temporadas:4},{nome:'BoJack Horseman',produtora:'Netflix',temporadas:6},
  {nome:'Futurama',produtora:'Fox',temporadas:12},{nome:'Os Simpsons',produtora:'Fox',temporadas:35},
  {nome:'South Park',produtora:'Comedy Central',temporadas:26},{nome:'Cyberpunk: Mercenários',produtora:'Studio Trigger',temporadas:1},
];

const SEED_FILMES = [
  // Filmes de Anime / Cultura Japonesa
  {nome:'A Viagem de Chihiro',ano:2001,genero:'Fantasia',diretor:'Hayao Miyazaki'},
  {nome:'Princesa Mononoke',ano:1997,genero:'Fantasia',diretor:'Hayao Miyazaki'},
  {nome:'O Castelo Animado',ano:2004,genero:'Fantasia',diretor:'Hayao Miyazaki'},
  {nome:'Meu Amigo Totoro',ano:1988,genero:'Fantasia',diretor:'Hayao Miyazaki'},
  {nome:'Túmulo dos Vagalumes',ano:1988,genero:'Drama',diretor:'Isao Takahata'},
  {nome:'Akira',ano:1988,genero:'Cyberpunk',diretor:'Katsuhiro Otomo'},
  {nome:'Ghost in the Shell',ano:1995,genero:'Cyberpunk',diretor:'Mamoru Oshii'},
  {nome:'Your Name',ano:2016,genero:'Romance',diretor:'Makoto Shinkai'},
  {nome:'O Tempo com Você',ano:2019,genero:'Romance',diretor:'Makoto Shinkai'},
  {nome:'Suzume',ano:2022,genero:'Aventura',diretor:'Makoto Shinkai'},
  {nome:'A Voz do Silêncio',ano:2016,genero:'Drama',diretor:'Naoko Yamada'},
  {nome:'Demon Slayer: Mugen Train',ano:2020,genero:'Ação',diretor:'Haruo Sotozaki'},
  {nome:'Jujutsu Kaisen 0',ano:2021,genero:'Ação',diretor:'Sunghoo Park'},
  {nome:'Dragon Ball Super: Broly',ano:2018,genero:'Ação',diretor:'Tatsuya Nagamine'},
  {nome:'One Piece Film: Red',ano:2022,genero:'Ação',diretor:'Goro Taniguchi'},
  {nome:'Evangelion: 3.0+1.0 Thrice Upon a Time',ano:2021,genero:'Mecha',diretor:'Hideaki Anno'},
  {nome:'Godzilla Minus One',ano:2023,genero:'Ação',diretor:'Takashi Yamazaki'},
  {nome:'Shin Godzilla',ano:2016,genero:'Ação',diretor:'Hideaki Anno'},
  {nome:'Alita: Anjo de Combate',ano:2019,genero:'Ação',diretor:'Robert Rodriguez'},
  {nome:'Final Fantasy VII: Advent Children',ano:2005,genero:'Ação',diretor:'Tetsuya Nomura'},
  
  // Cultura Pop Nerd (Heróis, Sci-Fi, Fantasia Clássica)
  {nome:'O Senhor dos Anéis: A Sociedade do Anel',ano:2001,genero:'Fantasia',diretor:'Peter Jackson'},
  {nome:'O Senhor dos Anéis: As Duas Torres',ano:2002,genero:'Fantasia',diretor:'Peter Jackson'},
  {nome:'O Senhor dos Anéis: O Retorno do Rei',ano:2003,genero:'Fantasia',diretor:'Peter Jackson'},
  {nome:'Star Wars: Episódio IV - Uma Nova Esperança',ano:1977,genero:'Ficção Científica',diretor:'George Lucas'},
  {nome:'Star Wars: O Império Contra-Ataca',ano:1980,genero:'Ficção Científica',diretor:'Irvin Kershner'},
  {nome:'Matrix',ano:1999,genero:'Ficção Científica',diretor:'Wachowskis'},
  {nome:'Batman: O Cavaleiro das Trevas',ano:2008,genero:'Ação',diretor:'Christopher Nolan'},
  {nome:'Vingadores: Guerra Infinita',ano:2018,genero:'Ação',diretor:'Russo Brothers'},
  {nome:'Vingadores: Ultimato',ano:2019,genero:'Ação',diretor:'Russo Brothers'},
  {nome:'Homem-Aranha: No Aranhaverso',ano:2018,genero:'Animação',diretor:'Peter Ramsey'},
  {nome:'Homem-Aranha: Através do Aranhaverso',ano:2023,genero:'Animação',diretor:'Joaquim Dos Santos'},
  {nome:'Deadpool',ano:2016,genero:'Ação',diretor:'Tim Miller'},
  {nome:'Deadpool & Wolverine',ano:2024,genero:'Ação',diretor:'Shawn Levy'},
  {nome:'Logan',ano:2017,genero:'Ação',diretor:'James Mangold'},
  {nome:'Coringa',ano:2019,genero:'Crime',diretor:'Todd Phillips'},
  {nome:'Duna: Parte Dois',ano:2024,genero:'Ficção Científica',diretor:'Denis Villeneuve'},
  {nome:'Interestelar',ano:2014,genero:'Ficção Científica',diretor:'Christopher Nolan'},
  {nome:'De Volta para o Futuro',ano:1985,genero:'Ficção Científica',diretor:'Robert Zemeckis'},
  {nome:'Jurassic Park',ano:1993,genero:'Ficção Científica',diretor:'Steven Spielberg'},
  {nome:'Harry Potter e o Prisioneiro de Azkaban',ano:2004,genero:'Fantasia',diretor:'Alfonso Cuarón'},
  {nome:'Scott Pilgrim Contra o Mundo',ano:2010,genero:'Comédia',diretor:'Edgar Wright'},
  {nome:'Mad Max: Estrada da Fúria',ano:2015,genero:'Ação',diretor:'George Miller'},
  {nome:'Transformers',ano:2007,genero:'Ficção Científica',diretor:'Michael Bay'},
  {nome:'O Exterminador do Futuro 2: O Julgamento Final',ano:1991,genero:'Ficção Científica',diretor:'James Cameron'},
  {nome:'Tudo em Todo o Lugar ao Mesmo Tempo',ano:2022,genero:'Ficção Científica',diretor:'Daniel Kwan'},
  {nome:'Super Mario Bros. O Filme',ano:2023,genero:'Animação',diretor:'Aaron Horvath'},
  {nome:'Sonic: O Filme',ano:2020,genero:'Ação',diretor:'Jeff Fowler'}
];

const SEED_MANGAS = [
  {nome:'Berserk',autor:'Kentaro Miura',capitulos:374,capa:'https://cdn.myanimelist.net/images/manga/1/157897l.jpg'},
  {nome:'Vagabond',autor:'Takehiko Inoue',capitulos:327,capa:'https://cdn.myanimelist.net/images/manga/2/181787l.jpg'},
  {nome:'Naruto',autor:'Masashi Kishimoto',capitulos:700,capa:'https://cdn.myanimelist.net/images/manga/3/249658l.jpg'},
  {nome:'Dragon Ball',autor:'Akira Toriyama',capitulos:520,capa:'https://cdn.myanimelist.net/images/manga/1/267793l.jpg'},
  {nome:'Death Note',autor:'Tsugumi Ohba',capitulos:108,capa:'https://cdn.myanimelist.net/images/manga/2/54453l.jpg'},
  {nome:'Fullmetal Alchemist',autor:'Hiromu Arakawa',capitulos:116,capa:'https://cdn.myanimelist.net/images/manga/1/27600l.jpg'},
  {nome:'Attack on Titan',autor:'Hajime Isayama',capitulos:141,capa:'https://cdn.myanimelist.net/images/manga/2/37846l.jpg'},
  {nome:'Hunter x Hunter',autor:'Yoshihiro Togashi',capitulos:400,capa:'https://cdn.myanimelist.net/images/manga/2/253119l.jpg'},
  {nome:'Slam Dunk',autor:'Takehiko Inoue',capitulos:276,capa:'https://cdn.myanimelist.net/images/manga/2/258749l.jpg'},
  {nome:'Tokyo Ghoul',autor:'Sui Ishida',capitulos:179,capa:'https://cdn.myanimelist.net/images/manga/3/114037l.jpg'},
  {nome:'Bleach',autor:'Tite Kubo',capitulos:686,capa:'https://cdn.myanimelist.net/images/manga/3/180031l.jpg'},
  {nome:'Demon Slayer',autor:'Koyoharu Gotouge',capitulos:205,capa:'https://cdn.myanimelist.net/images/manga/3/179023l.jpg'},
  {nome:'Jujutsu Kaisen',autor:'Gege Akutami',capitulos:271,capa:'https://cdn.myanimelist.net/images/manga/3/210341l.jpg'},
  {nome:'Chainsaw Man',autor:'Tatsuki Fujimoto',capitulos:185,capa:'https://cdn.myanimelist.net/images/manga/3/216464l.jpg'},
  {nome:'My Hero Academia',autor:'Kohei Horikoshi',capitulos:430,capa:'https://cdn.myanimelist.net/images/manga/1/209370l.jpg'},
  {nome:'Vinland Saga',autor:'Makoto Yukimura',capitulos:210,capa:'https://cdn.myanimelist.net/images/manga/2/188925l.jpg'},
  {nome:'Monster',autor:'Naoki Urasawa',capitulos:162,capa:'https://cdn.myanimelist.net/images/manga/3/258224l.jpg'},
  {nome:'20th Century Boys',autor:'Naoki Urasawa',capitulos:249,capa:'https://cdn.myanimelist.net/images/manga/5/260006l.jpg'},
  {nome:'Spy x Family',autor:'Tatsuya Endo',capitulos:100,capa:'https://cdn.myanimelist.net/images/manga/3/222295l.jpg'},
  {nome:'Mushoku Tensei',autor:'Rifujin na Magonote',capitulos:100,capa:'https://cdn.myanimelist.net/images/manga/1/262029l.jpg'},
  {nome:'Dandadan',autor:'Yukinobu Tatsu',capitulos:170,capa:'https://cdn.myanimelist.net/images/manga/1/259694l.jpg'},
  {nome:'Kaiju No. 8',autor:'Naoya Matsumoto',capitulos:110,capa:'https://cdn.myanimelist.net/images/manga/3/233474l.jpg'},
  {nome:'Blue Lock',autor:'Muneyuki Kaneshiro',capitulos:280,capa:'https://cdn.myanimelist.net/images/manga/1/232961l.jpg'},
  {nome:'Solo Leveling',autor:'Chugong',capitulos:200,capa:'https://cdn.myanimelist.net/images/manga/3/222295l.jpg'},
  {nome:'Fairy Tail',autor:'Hiro Mashima',capitulos:545,capa:'https://cdn.myanimelist.net/images/manga/2/175894l.jpg'},
  {nome:'Black Clover',autor:'Yuki Tabata',capitulos:370,capa:'https://cdn.myanimelist.net/images/manga/2/166124l.jpg'},
  {nome:'Oshi no Ko',autor:'Aka Akasaka',capitulos:162,capa:'https://cdn.myanimelist.net/images/manga/1/232860l.jpg'},
  {nome:'Dr. Stone',autor:'Riichiro Inagaki',capitulos:232,capa:'https://cdn.myanimelist.net/images/manga/3/200523l.jpg'},
  {nome:'Frieren',autor:'Kanehito Yamada',capitulos:130,capa:'https://cdn.myanimelist.net/images/manga/1/258945l.jpg'},
  {nome:'Gantz',autor:'Hiroya Oku',capitulos:383,capa:'https://cdn.myanimelist.net/images/manga/2/88813l.jpg'},
];

const SEED_HQS = [
  {nome:'Batman: O Cavaleiro das Trevas'},{nome:'Watchmen'},{nome:'Sandman'},
  {nome:'Batman: A Piada Mortal'},{nome:'Batman: Ano Um'},{nome:'All-Star Superman'},
  {nome:'Superman: Entre a Foice e o Martelo'},{nome:'O Reino do Amanhã'},{nome:'Crise nas Infinitas Terras'},
  {nome:'X-Men: Dias de um Futuro Esquecido'},{nome:'X-Men: A Saga da Fênix Negra'},{nome:'Demolidor: A Queda de Murdock'},
  {nome:'Homem-Aranha: A Última Caçada de Kraven'},{nome:'Guerras Secretas'},{nome:'Guerra Civil'},
  {nome:'Desafio Infinito'},{nome:'A Morte do Superman'},{nome:'V de Vingança'},
  {nome:'Invencível'},{nome:'The Boys'},{nome:'Saga'},
  {nome:'Scott Pilgrim'},{nome:'Hellboy'},{nome:'Spawn'},
  {nome:'Kick-Ass'},{nome:'O Velho Logan'},{nome:'Sin City'},
  {nome:'Preacher'},{nome:'Y: O Último Homem'},{nome:'Tartarugas Ninja: O Último Ronin'},
];
