// seed-data.js — Dados para cadastro global em massa
const SEED_ANIMES = [
  {nome:'Fullmetal Alchemist: Brotherhood',estudio:'Bones',genero:'Ação, Aventura, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1208/94745l.jpg'},
  {nome:'Death Note',estudio:'Madhouse',genero:'Suspense, Sobrenatural',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/9/9453l.jpg'},
  {nome:'Shingeki no Kyojin',estudio:'Wit Studio',genero:'Ação, Drama, Suspense',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/10/47347l.jpg'},
  {nome:'Steins;Gate',estudio:'White Fox',genero:'Ficção Científica, Suspense',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/5/73199l.jpg'},
  {nome:'Hunter x Hunter (2011)',estudio:'Madhouse',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1337/99013l.jpg'},
  {nome:'Code Geass',estudio:'Sunrise',genero:'Ação, Mecha, Drama',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/5/50331l.jpg'},
  {nome:'Cowboy Bebop',estudio:'Sunrise',genero:'Ação, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/4/19644l.jpg'},
  {nome:'Mob Psycho 100',estudio:'Bones',genero:'Ação, Comédia',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/8/80356l.jpg'},
  {nome:'Vinland Saga',estudio:'Wit Studio',genero:'Ação, Aventura, Drama',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1500/103005l.jpg'},
  {nome:'Jujutsu Kaisen',estudio:'MAPPA',genero:'Ação, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1171/109222l.jpg'},
  {nome:'Demon Slayer',estudio:'ufotable',genero:'Ação, Sobrenatural',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/1286/99889l.jpg'},
  {nome:'My Hero Academia',estudio:'Bones',genero:'Ação, Super Poderes',temporadas:7,capa:'https://cdn.myanimelist.net/images/anime/10/78745l.jpg'},
  {nome:'Naruto Shippuden',estudio:'Pierrot',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/5/17407l.jpg'},
  {nome:'Dragon Ball Super',estudio:'Toei Animation',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/7/74606l.jpg'},
  {nome:'Bleach: Thousand-Year Blood War',estudio:'Pierrot',genero:'Ação, Aventura',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/1908/135431l.jpg'},
  {nome:'Chainsaw Man',estudio:'MAPPA',genero:'Ação, Terror',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1806/126216l.jpg'},
  {nome:'Spy x Family',estudio:'Wit Studio',genero:'Ação, Comédia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1441/122795l.jpg'},
  {nome:'Neon Genesis Evangelion',estudio:'Gainax',genero:'Mecha, Drama, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1314/108941l.jpg'},
  {nome:'Gintama',estudio:'Sunrise',genero:'Ação, Comédia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/10/73274l.jpg'},
  {nome:'One Punch Man',estudio:'Madhouse',genero:'Ação, Comédia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/12/76049l.jpg'},
  {nome:'Re:Zero',estudio:'White Fox',genero:'Drama, Fantasia, Suspense',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1522/128039l.jpg'},
  {nome:'Violet Evergarden',estudio:'Kyoto Animation',genero:'Drama, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1795/95088l.jpg'},
  {nome:'Made in Abyss',estudio:'Kinema Citrus',genero:'Aventura, Drama, Fantasia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/6/86733l.jpg'},
  {nome:'Sword Art Online',estudio:'A-1 Pictures',genero:'Ação, Aventura, Fantasia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/11/39717l.jpg'},
  {nome:'Tokyo Ghoul',estudio:'Pierrot',genero:'Ação, Terror, Sobrenatural',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/5/64449l.jpg'},
  {nome:'Parasyte',estudio:'Madhouse',genero:'Ação, Terror, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/3/73178l.jpg'},
  {nome:'Mushoku Tensei',estudio:'Studio Bind',genero:'Aventura, Drama, Fantasia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1530/117776l.jpg'},
  {nome:'Frieren: Beyond Journey\'s End',estudio:'Madhouse',genero:'Aventura, Drama, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1015/138006l.jpg'},
  {nome:'Solo Leveling',estudio:'A-1 Pictures',genero:'Ação, Aventura, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1908/141575l.jpg'},
  {nome:'Oshi no Ko',estudio:'Doga Kobo',genero:'Drama, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1812/134736l.jpg'},
  {nome:'Your Lie in April',estudio:'A-1 Pictures',genero:'Drama, Música, Romance',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/3/67177l.jpg'},
  {nome:'Haikyuu!!',estudio:'Production I.G',genero:'Esportes, Comédia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/7/76014l.jpg'},
  {nome:'Toradora!',estudio:'J.C.Staff',genero:'Comédia, Romance',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/5/22894l.jpg'},
  {nome:'Erased',estudio:'A-1 Pictures',genero:'Mistério, Suspense',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/10/77957l.jpg'},
  {nome:'The Promised Neverland',estudio:'CloverWorks',genero:'Mistério, Suspense',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1830/118780l.jpg'},
  {nome:'Samurai Champloo',estudio:'Manglobe',genero:'Ação, Aventura',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1375/121599l.jpg'},
  {nome:'Black Clover',estudio:'Pierrot',genero:'Ação, Fantasia',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/2/88336l.jpg'},
  {nome:'Fire Force',estudio:'David Production',genero:'Ação, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1286/101640l.jpg'},
  {nome:'Dr. Stone',estudio:'TMS Entertainment',genero:'Aventura, Ficção Científica',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/1613/102576l.jpg'},
  {nome:'Overlord',estudio:'Madhouse',genero:'Ação, Aventura, Fantasia',temporadas:4,capa:'https://cdn.myanimelist.net/images/anime/7/88019l.jpg'},
  {nome:'Konosuba',estudio:'Studio Deen',genero:'Aventura, Comédia, Fantasia',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/8/77831l.jpg'},
  {nome:'Assassination Classroom',estudio:'Lerche',genero:'Ação, Comédia',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/5/75639l.jpg'},
  {nome:'Noragami',estudio:'Bones',genero:'Ação, Aventura, Sobrenatural',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/9/67899l.jpg'},
  {nome:'Blue Lock',estudio:'8bit',genero:'Esportes',temporadas:2,capa:'https://cdn.myanimelist.net/images/anime/1258/126929l.jpg'},
  {nome:'Kaiju No. 8',estudio:'Production I.G',genero:'Ação, Ficção Científica',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1137/141622l.jpg'},
  {nome:'Dandadan',estudio:'Science SARU',genero:'Ação, Comédia, Sobrenatural',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1032/142083l.jpg'},
  {nome:'Hell\'s Paradise',estudio:'MAPPA',genero:'Ação, Aventura, Sobrenatural',temporadas:1,capa:'https://cdn.myanimelist.net/images/anime/1002/133399l.jpg'},
  {nome:'Tokyo Revengers',estudio:'LIDENFILMS',genero:'Ação, Drama',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/1839/122012l.jpg'},
  {nome:'Bungo Stray Dogs',estudio:'Bones',genero:'Ação, Mistério, Sobrenatural',temporadas:5,capa:'https://cdn.myanimelist.net/images/anime/3/74088l.jpg'},
  {nome:'Kaguya-sama: Love is War',estudio:'A-1 Pictures',genero:'Comédia, Romance',temporadas:3,capa:'https://cdn.myanimelist.net/images/anime/1295/106551l.jpg'},
];

const SEED_DESENHOS = [
  // ── Cartoon Network ──────────────────────────────────────────────
  {nome:'Apenas um Show',produtora:'Cartoon Network',temporadas:8},
  {nome:'Hora de Aventura',produtora:'Cartoon Network',temporadas:10},
  {nome:'O Incrível Mundo de Gumball',produtora:'Cartoon Network',temporadas:6},
  {nome:'Steven Universe',produtora:'Cartoon Network',temporadas:6},
  {nome:'Jovens Titãs',produtora:'Cartoon Network',temporadas:5},
  {nome:'Ben 10',produtora:'Cartoon Network',temporadas:4},
  {nome:'As Meninas Superpoderosas',produtora:'Cartoon Network',temporadas:6},
  {nome:'O Laboratório de Dexter',produtora:'Cartoon Network',temporadas:4},
  {nome:'Samurai Jack',produtora:'Cartoon Network',temporadas:5},
  {nome:'Coragem, o Cão Covarde',produtora:'Cartoon Network',temporadas:4},
  {nome:'KND: A Turma do Bairro',produtora:'Cartoon Network',temporadas:6},
  {nome:'Du, Dudu e Edu',produtora:'Cartoon Network',temporadas:6},
  {nome:'Mutante Rex',produtora:'Cartoon Network',temporadas:3},
  {nome:'Mansão Foster para Amigos Imaginários',produtora:'Cartoon Network',temporadas:6},
  {nome:'As Terríveis Aventuras de Billy e Mandy',produtora:'Cartoon Network',temporadas:6},
  {nome:'Chowder',produtora:'Cartoon Network',temporadas:3},
  {nome:'Johnny Bravo',produtora:'Cartoon Network',temporadas:4},
  {nome:'A Vaca e o Frango',produtora:'Cartoon Network',temporadas:4},
  {nome:'O Segredo Além do Jardim',produtora:'Cartoon Network',temporadas:1},
  {nome:'Trem Infinito',produtora:'Cartoon Network',temporadas:4},
  {nome:'Acampamento de Verão',produtora:'Cartoon Network',temporadas:6},
  {nome:'Craig do Riacho',produtora:'Cartoon Network',temporadas:5},
  {nome:'Vilanesco',produtora:'Cartoon Network',temporadas:1},
  {nome:'As Trapalhadas de Flapjack',produtora:'Cartoon Network',temporadas:3},
  {nome:'Ursos sem Curso',produtora:'Cartoon Network',temporadas:4},
  // ── Nickelodeon ──────────────────────────────────────────────────
  {nome:'Bob Esponja',produtora:'Nickelodeon',temporadas:14},
  {nome:'Avatar: A Lenda de Aang',produtora:'Nickelodeon',temporadas:3},
  {nome:'A Lenda de Korra',produtora:'Nickelodeon',temporadas:4},
  {nome:'Danny Phantom',produtora:'Nickelodeon',temporadas:3},
  {nome:'Padrinhos Mágicos',produtora:'Nickelodeon',temporadas:10},
  {nome:'Invasor Zim',produtora:'Nickelodeon',temporadas:2},
  {nome:'A Vida Moderna de Rocko',produtora:'Nickelodeon',temporadas:4},
  {nome:'Tartarugas Ninja (2012)',produtora:'Nickelodeon',temporadas:5},
  // ── Outros (já cadastrados antes) ───────────────────────────────
  {nome:'Invencível',produtora:'Amazon Prime',temporadas:3},
  // ── DIVISOR: Lego Ninjago em diante (CN/Nick novos) ─────────────
  {nome:'Lego Ninjago',produtora:'Cartoon Network',temporadas:15},
  {nome:'Ben 10: Força Alienígena',produtora:'Cartoon Network',temporadas:3},
  {nome:'Ben 10: Supremacia Alienígena',produtora:'Cartoon Network',temporadas:3},
  {nome:'Ben 10: Omniverse',produtora:'Cartoon Network',temporadas:8},
  {nome:'Clarence',produtora:'Cartoon Network',temporadas:3},
  {nome:'Batman: A Série Animada',produtora:'Cartoon Network',temporadas:4},
  {nome:'Liga da Justiça',produtora:'Cartoon Network',temporadas:2},
  {nome:'Liga da Justiça Sem Limites',produtora:'Cartoon Network',temporadas:3},
  {nome:'Super Choque',produtora:'Cartoon Network',temporadas:4},
  {nome:'Titio Avô',produtora:'Cartoon Network',temporadas:5},
  {nome:'Rick and Morty',produtora:'Adult Swim',temporadas:7},
  {nome:'South Park',produtora:'Comedy Central',temporadas:27},
  {nome:'Phineas e Ferb',produtora:'Disney',temporadas:5},
  {nome:'Gravity Falls',produtora:'Disney',temporadas:2},
  {nome:'Kim Possible',produtora:'Disney',temporadas:4},
  {nome:'Star vs. As Forças do Mal',produtora:'Disney',temporadas:4},
];

const SEED_FILMES = [
  // Filmes de Anime / Cultura Japonesa
  {nome:'A Viagem de Chihiro',ano:2001,genero:'Fantasia',diretor:'Hayao Miyazaki',capa:'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg'},
  {nome:'Princesa Mononoke',ano:1997,genero:'Fantasia',diretor:'Hayao Miyazaki',capa:'https://image.tmdb.org/t/p/w500/jHYJDIiQLBoYAkoh475rN2MBONN.jpg'},
  {nome:'O Castelo Animado',ano:2004,genero:'Fantasia',diretor:'Hayao Miyazaki',capa:'https://image.tmdb.org/t/p/w500/TkPDKNBHg7MFSJfaUzqZo2WUUE.jpg'},
  {nome:'Meu Amigo Totoro',ano:1988,genero:'Fantasia',diretor:'Hayao Miyazaki',capa:'https://image.tmdb.org/t/p/w500/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg'},
  {nome:'Túmulo dos Vagalumes',ano:1988,genero:'Drama',diretor:'Isao Takahata',capa:'https://image.tmdb.org/t/p/w500/k9tv1rXZbOD5zHQoQWa0WX6MUBK.jpg'},
  {nome:'Akira',ano:1988,genero:'Cyberpunk',diretor:'Katsuhiro Otomo',capa:'https://image.tmdb.org/t/p/w500/yI8tL92vGhwR0AFET4xNzCAGLuM.jpg'},
  {nome:'Ghost in the Shell',ano:1995,genero:'Cyberpunk',diretor:'Mamoru Oshii',capa:'https://image.tmdb.org/t/p/w500/9FhKGWOBNkTxlVRSqDkbNMTBEd8.jpg'},
  {nome:'Your Name',ano:2016,genero:'Romance',diretor:'Makoto Shinkai',capa:'https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg'},
  {nome:'O Tempo com Você',ano:2019,genero:'Romance',diretor:'Makoto Shinkai',capa:'https://image.tmdb.org/t/p/w500/fQDimRjMRhFiXMhgXKlnFcAknIq.jpg'},
  {nome:'Suzume',ano:2022,genero:'Aventura',diretor:'Makoto Shinkai',capa:'https://image.tmdb.org/t/p/w500/iEhMBBF6LvkAkR4DLWJ9gxPr5MJ.jpg'},
  {nome:'A Voz do Silêncio',ano:2016,genero:'Drama',diretor:'Naoko Yamada',capa:'https://image.tmdb.org/t/p/w500/aRnMZYoAIgsdcSmKpMBW4nDpxHs.jpg'},
  {nome:'Demon Slayer: Mugen Train',ano:2020,genero:'Ação',diretor:'Haruo Sotozaki',capa:'https://image.tmdb.org/t/p/w500/h8Rb9gBr48ODIwYwhXl7MRy0LNUD.jpg'},
  {nome:'Jujutsu Kaisen 0',ano:2021,genero:'Ação',diretor:'Sunghoo Park',capa:'https://image.tmdb.org/t/p/w500/23QgNTxbJqFKYVzpEVijfgXoFBV.jpg'},
  {nome:'Dragon Ball Super: Broly',ano:2018,genero:'Ação',diretor:'Tatsuya Nagamine',capa:'https://image.tmdb.org/t/p/w500/s1TgJJTNwdGPh0VrVUUCNEXvPnZ.jpg'},
  {nome:'One Piece Film: Red',ano:2022,genero:'Ação',diretor:'Goro Taniguchi',capa:'https://image.tmdb.org/t/p/w500/qIjaSmwHHyJkHaLz8GRXbS55Zph.jpg'},
  {nome:'Evangelion: 3.0+1.0 Thrice Upon a Time',ano:2021,genero:'Mecha',diretor:'Hideaki Anno',capa:'https://image.tmdb.org/t/p/w500/jDwZavHo99JtGsCyRd4vVSMFMbQ.jpg'},
  {nome:'Godzilla Minus One',ano:2023,genero:'Ação',diretor:'Takashi Yamazaki',capa:'https://image.tmdb.org/t/p/w500/hkxxMIGaiCTmrEArK7J56rvbom4.jpg'},
  {nome:'Shin Godzilla',ano:2016,genero:'Ação',diretor:'Hideaki Anno',capa:'https://image.tmdb.org/t/p/w500/pHXqnJpnGJEODLFYSbN5Gv97HCG.jpg'},
  {nome:'Alita: Anjo de Combate',ano:2019,genero:'Ação',diretor:'Robert Rodriguez',capa:'https://image.tmdb.org/t/p/w500/hEjK9A9BkNXejFW4tfacVAEHtkn.jpg'},
  {nome:'Final Fantasy VII: Advent Children',ano:2005,genero:'Ação',diretor:'Tetsuya Nomura',capa:'https://image.tmdb.org/t/p/w500/6lXFbcOLSFG2KVoiKoVVGq0YWYL.jpg'},

  // Cultura Pop Nerd (Heróis, Sci-Fi, Fantasia Clássica)
  {nome:'O Senhor dos Anéis: A Sociedade do Anel',ano:2001,genero:'Fantasia',diretor:'Peter Jackson',capa:'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg'},
  {nome:'O Senhor dos Anéis: As Duas Torres',ano:2002,genero:'Fantasia',diretor:'Peter Jackson',capa:'https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg'},
  {nome:'O Senhor dos Anéis: O Retorno do Rei',ano:2003,genero:'Fantasia',diretor:'Peter Jackson',capa:'https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg'},
  {nome:'Star Wars: Episódio IV - Uma Nova Esperança',ano:1977,genero:'Ficção Científica',diretor:'George Lucas',capa:'https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg'},
  {nome:'Star Wars: O Império Contra-Ataca',ano:1980,genero:'Ficção Científica',diretor:'Irvin Kershner',capa:'https://image.tmdb.org/t/p/w500/2l05cFWJacyIX65LVjghHOFB6f4.jpg'},
  {nome:'Matrix',ano:1999,genero:'Ficção Científica',diretor:'Wachowskis',capa:'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg'},
  {nome:'Batman: O Cavaleiro das Trevas',ano:2008,genero:'Ação',diretor:'Christopher Nolan',capa:'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg'},
  {nome:'Vingadores: Guerra Infinita',ano:2018,genero:'Ação',diretor:'Russo Brothers',capa:'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg'},
  {nome:'Vingadores: Ultimato',ano:2019,genero:'Ação',diretor:'Russo Brothers',capa:'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg'},
  {nome:'Homem-Aranha: No Aranhaverso',ano:2018,genero:'Animação',diretor:'Peter Ramsey',capa:'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg'},
  {nome:'Homem-Aranha: Através do Aranhaverso',ano:2023,genero:'Animação',diretor:'Joaquim Dos Santos',capa:'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg'},
  {nome:'Deadpool',ano:2016,genero:'Ação',diretor:'Tim Miller',capa:'https://image.tmdb.org/t/p/w500/inVq3FRqcYIRl2la8iZikYYxFNR.jpg'},
  {nome:'Deadpool & Wolverine',ano:2024,genero:'Ação',diretor:'Shawn Levy',capa:'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg'},
  {nome:'Logan',ano:2017,genero:'Ação',diretor:'James Mangold',capa:'https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg'},
  {nome:'Coringa',ano:2019,genero:'Crime',diretor:'Todd Phillips',capa:'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg'},
  {nome:'Duna: Parte Dois',ano:2024,genero:'Ficção Científica',diretor:'Denis Villeneuve',capa:'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg'},
  {nome:'Interestelar',ano:2014,genero:'Ficção Científica',diretor:'Christopher Nolan',capa:'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg'},
  {nome:'De Volta para o Futuro',ano:1985,genero:'Ficção Científica',diretor:'Robert Zemeckis',capa:'https://image.tmdb.org/t/p/w500/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg'},
  {nome:'Jurassic Park',ano:1993,genero:'Ficção Científica',diretor:'Steven Spielberg',capa:'https://image.tmdb.org/t/p/w500/oU7Oq2kFAAlGqbU4VoAE36g4hoI.jpg'},
  {nome:'Harry Potter e o Prisioneiro de Azkaban',ano:2004,genero:'Fantasia',diretor:'Alfonso Cuarón',capa:'https://image.tmdb.org/t/p/w500/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg'},
  {nome:'Scott Pilgrim Contra o Mundo',ano:2010,genero:'Comédia',diretor:'Edgar Wright',capa:'https://image.tmdb.org/t/p/w500/uNpxRFGtKxqfHkqiSCBk0OqN6hT.jpg'},
  {nome:'Mad Max: Estrada da Fúria',ano:2015,genero:'Ação',diretor:'George Miller',capa:'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg'},
  {nome:'Transformers',ano:2007,genero:'Ficção Científica',diretor:'Michael Bay',capa:'https://image.tmdb.org/t/p/w500/7ZpXGSMiW0CTuHHlEGLEVMlGMef.jpg'},
  {nome:'O Exterminador do Futuro 2: O Julgamento Final',ano:1991,genero:'Ficção Científica',diretor:'James Cameron',capa:'https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5gi3JOGQvjko4l.jpg'},
  {nome:'Tudo em Todo o Lugar ao Mesmo Tempo',ano:2022,genero:'Ficção Científica',diretor:'Daniel Kwan',capa:'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg'},
  {nome:'Super Mario Bros. O Filme',ano:2023,genero:'Animação',diretor:'Aaron Horvath',capa:'https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThrVvA6mA2B5ggkM.jpg'},
  {nome:'Sonic: O Filme',ano:2020,genero:'Ação',diretor:'Jeff Fowler',capa:'https://image.tmdb.org/t/p/w500/aQvJ5WPzZgYVDrxLX4R6cLJCgaQ.jpg'},
  {nome:'Pantera Negra',ano:2018,genero:'Ação',diretor:'Ryan Coogler',capa:'https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg'},
  {nome:'Guardiões da Galáxia',ano:2014,genero:'Ação',diretor:'James Gunn',capa:'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg'},
  {nome:'Doutor Estranho',ano:2016,genero:'Ação',diretor:'Scott Derrickson',capa:'https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg'},
];

const SEED_MANGAS = [
  {nome:'Berserk',autor:'Kentaro Miura',volumes:41,capa:'https://cdn.myanimelist.net/images/manga/1/157897l.jpg'},
  {nome:'Vagabond',autor:'Takehiko Inoue',volumes:37,capa:'https://cdn.myanimelist.net/images/manga/2/181787l.jpg'},
  {nome:'Naruto',autor:'Masashi Kishimoto',volumes:72,capa:'https://cdn.myanimelist.net/images/manga/3/249658l.jpg'},
  {nome:'Dragon Ball',autor:'Akira Toriyama',volumes:42,capa:'https://cdn.myanimelist.net/images/manga/1/267793l.jpg'},
  {nome:'Death Note',autor:'Tsugumi Ohba',volumes:12,capa:'https://cdn.myanimelist.net/images/manga/2/54453l.jpg'},
  {nome:'Fullmetal Alchemist',autor:'Hiromu Arakawa',volumes:27,capa:'https://cdn.myanimelist.net/images/manga/1/27600l.jpg'},
  {nome:'Attack on Titan',autor:'Hajime Isayama',volumes:34,capa:'https://cdn.myanimelist.net/images/manga/2/37846l.jpg'},
  {nome:'Hunter x Hunter',autor:'Yoshihiro Togashi',volumes:37,capa:'https://cdn.myanimelist.net/images/manga/2/253119l.jpg'},
  {nome:'Slam Dunk',autor:'Takehiko Inoue',volumes:31,capa:'https://cdn.myanimelist.net/images/manga/2/258749l.jpg'},
  {nome:'Tokyo Ghoul',autor:'Sui Ishida',volumes:14,capa:'https://cdn.myanimelist.net/images/manga/3/114037l.jpg'},
  {nome:'Bleach',autor:'Tite Kubo',volumes:74,capa:'https://cdn.myanimelist.net/images/manga/3/180031l.jpg'},
  {nome:'Demon Slayer',autor:'Koyoharu Gotouge',volumes:23,capa:'https://cdn.myanimelist.net/images/manga/3/179023l.jpg'},
  {nome:'Jujutsu Kaisen',autor:'Gege Akutami',volumes:27,capa:'https://cdn.myanimelist.net/images/manga/3/210341l.jpg'},
  {nome:'Chainsaw Man',autor:'Tatsuki Fujimoto',volumes:17,capa:'https://cdn.myanimelist.net/images/manga/3/216464l.jpg'},
  {nome:'My Hero Academia',autor:'Kohei Horikoshi',volumes:40,capa:'https://cdn.myanimelist.net/images/manga/1/209370l.jpg'},
  {nome:'Vinland Saga',autor:'Makoto Yukimura',volumes:27,capa:'https://cdn.myanimelist.net/images/manga/2/188925l.jpg'},
  {nome:'Monster',autor:'Naoki Urasawa',volumes:18,capa:'https://cdn.myanimelist.net/images/manga/3/258224l.jpg'},
  {nome:'20th Century Boys',autor:'Naoki Urasawa',volumes:22,capa:'https://cdn.myanimelist.net/images/manga/5/260006l.jpg'},
  {nome:'Spy x Family',autor:'Tatsuya Endo',volumes:13,capa:'https://cdn.myanimelist.net/images/manga/3/222295l.jpg'},
  {nome:'Mushoku Tensei',autor:'Rifujin na Magonote',volumes:20,capa:'https://cdn.myanimelist.net/images/manga/1/262029l.jpg'},
  {nome:'Dandadan',autor:'Yukinobu Tatsu',volumes:14,capa:'https://cdn.myanimelist.net/images/manga/1/259694l.jpg'},
  {nome:'Kaiju No. 8',autor:'Naoya Matsumoto',volumes:12,capa:'https://cdn.myanimelist.net/images/manga/3/233474l.jpg'},
  {nome:'Blue Lock',autor:'Muneyuki Kaneshiro',volumes:28,capa:'https://cdn.myanimelist.net/images/manga/1/232961l.jpg'},
  {nome:'Solo Leveling',autor:'Chugong',volumes:9,capa:'https://cdn.myanimelist.net/images/manga/3/222295l.jpg'},
  {nome:'Fairy Tail',autor:'Hiro Mashima',volumes:63,capa:'https://cdn.myanimelist.net/images/manga/2/175894l.jpg'},
  {nome:'Black Clover',autor:'Yuki Tabata',volumes:36,capa:'https://cdn.myanimelist.net/images/manga/2/166124l.jpg'},
  {nome:'Oshi no Ko',autor:'Aka Akasaka',volumes:14,capa:'https://cdn.myanimelist.net/images/manga/1/232860l.jpg'},
  {nome:'Dr. Stone',autor:'Riichiro Inagaki',volumes:26,capa:'https://cdn.myanimelist.net/images/manga/3/200523l.jpg'},
  {nome:'Frieren',autor:'Kanehito Yamada',volumes:12,capa:'https://cdn.myanimelist.net/images/manga/1/258945l.jpg'},
  {nome:'Gantz',autor:'Hiroya Oku',volumes:37,capa:'https://cdn.myanimelist.net/images/manga/2/88813l.jpg'},
];

const SEED_HQS = [
  {nome:'Batman: O Cavaleiro das Trevas',edicoes:4,capa:'https://upload.wikimedia.org/wikipedia/en/8/8c/Dark_knight_returns.jpg'},
  {nome:'Watchmen',edicoes:12,capa:'https://upload.wikimedia.org/wikipedia/en/a/a2/Watchmen%2C_issue_1.jpg'},
  {nome:'Sandman',edicoes:75,capa:'https://upload.wikimedia.org/wikipedia/en/f/f4/Sandman_1_-_comics.jpg'},
  {nome:'Batman: A Piada Mortal',edicoes:1,capa:'https://upload.wikimedia.org/wikipedia/en/a/a6/The_Killing_Joke.jpg'},
  {nome:'Batman: Ano Um',edicoes:4,capa:'https://upload.wikimedia.org/wikipedia/en/4/43/Batman_Year_One_1.jpg'},
  {nome:'All-Star Superman',edicoes:12,capa:'https://upload.wikimedia.org/wikipedia/en/3/34/All-Star_Superman_1.jpg'},
  {nome:'Superman: Entre a Foice e o Martelo',edicoes:3,capa:'https://upload.wikimedia.org/wikipedia/en/1/14/Superman_RedSon_1.jpg'},
  {nome:'O Reino do Amanhã',edicoes:4,capa:'https://upload.wikimedia.org/wikipedia/en/1/14/KingdomCome1.jpg'},
  {nome:'Crise nas Infinitas Terras',edicoes:12,capa:'https://upload.wikimedia.org/wikipedia/en/9/9e/Crisis_on_Infinite_Earths_1.jpg'},
  {nome:'X-Men: Dias de um Futuro Esquecido',edicoes:2,capa:'https://upload.wikimedia.org/wikipedia/en/2/2e/X-Men141.jpg'},
  {nome:'X-Men: A Saga da Fênix Negra',edicoes:10,capa:'https://upload.wikimedia.org/wikipedia/en/7/7b/XMen134.jpg'},
  {nome:'Demolidor: A Queda de Murdock',edicoes:7,capa:'https://upload.wikimedia.org/wikipedia/en/6/67/Daredevil_Born_Again_tpb.jpg'},
  {nome:'Homem-Aranha: A Última Caçada de Kraven',edicoes:6,capa:'https://upload.wikimedia.org/wikipedia/en/f/f0/KravensLastHunt1.jpg'},
  {nome:'Guerras Secretas',edicoes:12,capa:'https://upload.wikimedia.org/wikipedia/en/b/b6/SecretWars1.jpg'},
  {nome:'Guerra Civil',edicoes:7,capa:'https://upload.wikimedia.org/wikipedia/en/f/f8/CivilWar1.jpg'},
  {nome:'Desafio Infinito',edicoes:6,capa:'https://upload.wikimedia.org/wikipedia/en/9/99/InfinityGauntlet1.jpg'},
  {nome:'A Morte do Superman',edicoes:1,capa:'https://upload.wikimedia.org/wikipedia/en/8/8d/Death_of_Superman_TPB.jpg'},
  {nome:'V de Vingança',edicoes:10,capa:'https://upload.wikimedia.org/wikipedia/en/b/b9/V-for-vendetta.jpg'},
  {nome:'Invencível',edicoes:144,capa:'https://upload.wikimedia.org/wikipedia/en/3/3b/InvincibleComic1.jpg'},
  {nome:'The Boys',edicoes:72,capa:'https://upload.wikimedia.org/wikipedia/en/d/db/The_Boys_1.jpg'},
  {nome:'Saga',edicoes:66,capa:'https://upload.wikimedia.org/wikipedia/en/4/4e/Saga_1.jpg'},
  {nome:'Scott Pilgrim',edicoes:6,capa:'https://upload.wikimedia.org/wikipedia/en/7/77/Scott_Pilgrim_vol1_cover.jpg'},
  {nome:'Hellboy',edicoes:12,capa:'https://upload.wikimedia.org/wikipedia/en/b/b9/Hellboy01.jpg'},
  {nome:'Spawn',edicoes:350,capa:'https://upload.wikimedia.org/wikipedia/en/d/d1/Spawn1.jpg'},
  {nome:'Kick-Ass',edicoes:8,capa:'https://upload.wikimedia.org/wikipedia/en/e/e7/Kick-Ass_1.jpg'},
  {nome:'O Velho Logan',edicoes:8,capa:'https://upload.wikimedia.org/wikipedia/en/0/0f/OldMan_Logan_1.jpg'},
  {nome:'Sin City',edicoes:7,capa:'https://upload.wikimedia.org/wikipedia/en/4/46/Sin_City_v1_tpb.jpg'},
  {nome:'Preacher',edicoes:66,capa:'https://upload.wikimedia.org/wikipedia/en/5/51/Preacher_Vol_1_1.jpg'},
  {nome:'Y: O Último Homem',edicoes:60,capa:'https://upload.wikimedia.org/wikipedia/en/d/df/Y_The_Last_Man_1.jpg'},
  {nome:'Tartarugas Ninja: O Último Ronin',edicoes:5,capa:'https://upload.wikimedia.org/wikipedia/en/f/f5/The_Last_Ronin_1.jpg'},
];

// Alias de busca no TMDB para evitar ambiguidade por nome local.
// Usado pela Fase 2 para encontrar a série correta.
const SEED_TMDB_SEARCH_ALIASES = {
  // Desenhos
  'Apenas um Show': 'Regular Show',
  'Hora de Aventura': 'Adventure Time',
  'O Incrível Mundo de Gumball': 'The Amazing World of Gumball',
  'Jovens Titãs': 'Teen Titans',
  'Jovens Titãs Clássico': 'Teen Titans',
  'Ben 10': 'Ben 10 (2005)',
  'Ben 10: Força Alienígena': 'Ben 10: Alien Force',
  'Ben 10: Supremacia Alienígena': 'Ben 10: Ultimate Alien',
  'KND: A Turma do Bairro': 'Codename: Kids Next Door',
  'Du, Dudu e Edu': 'Ed, Edd n Eddy',
  'Mutante Rex': 'Generator Rex',
  'Mansão Foster para Amigos Imaginários': "Foster's Home for Imaginary Friends",
  'As Terríveis Aventuras de Billy e Mandy': 'The Grim Adventures of Billy & Mandy',
  'Trem Infinito': 'Infinity Train',
  'Acampamento de Verão': 'Camp Lazlo',
  'Lego Ninjago': 'Ninjago: Masters of Spinjitzu',
  'Batman: A Série Animada': 'Batman: The Animated Series',
  'Liga da Justiça': 'Justice League',
  'Liga da Justiça Sem Limites': 'Justice League Unlimited',
  'Super Choque': 'Static Shock',
  'Bob Esponja': 'SpongeBob SquarePants',
  'Avatar: A Lenda de Aang': 'Avatar: The Last Airbender',
  'A Lenda de Korra': 'The Legend of Korra',
  'Padrinhos Mágicos': 'The Fairly OddParents',
  'Os Padrinhos Mágicos': 'The Fairly OddParents',
  'Invasor Zim': 'Invader ZIM',
  'A Vida Moderna de Rocko': "Rocko's Modern Life",
  'Rocko: A Vida Moderna': "Rocko's Modern Life",
  'Tartarugas Ninja (2012)': 'Teenage Mutant Ninja Turtles',
  // Animes
  'Shingeki no Kyojin': 'Attack on Titan',
  'Demon Slayer': 'Demon Slayer: Kimetsu no Yaiba',
  'One Punch Man': 'One-Punch Man',
  'Naruto Shippuden': 'Naruto: Shippuden',
  'Hunter x Hunter (2011)': 'Hunter x Hunter',
  'Re:Zero': 'Re:Zero -Starting Life in Another World-',
  'Code Geass': 'Code Geass: Lelouch of the Rebellion',
  'Parasyte': 'Parasyte -the maxim-',
  'Konosuba': "KonoSuba: God's Blessing on This Wonderful World!",
  'Mushoku Tensei': 'Mushoku Tensei: Jobless Reincarnation'
  ,
  // Novos desenhos
  'Titio Avô': 'Uncle Grandpa',
  'Phineas e Ferb': 'Phineas and Ferb',
  'Star vs. As Forças do Mal': 'Star vs. the Forces of Evil',
  // Novos animes
  'Kaguya-sama: Love is War': 'Kaguya-sama: Love Is War'
};
